# Generated by Django 4.2.16 on 2024-09-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
